---
title: "Philip T. Patton"
description: Graduate Research Assistant & NOAA QUEST Fellow

---

[Downloadable version](patton-cv.pdf)

## Education

- Ph.D., Marine Biology, Hawaiʻi Institute of Marine Biology, 2025
  - Chair: Lars Bejder
- M.S., Fisheries, Wildlife, and Conservation Biology, North Carolina State University, 2016
  - Chair: Krishna Pacifici
- B.S., Conservation Biology, SUNY College of Environmental Science and Forestry, 2013

## Research Experience

- Quantitative Ecologist, Migratory Bird Center, Smithsonian's National Zoo and Conservation Biology Institute, 2025 - Present
- NOAA QUEST Fellow, Pacific Islands Fisheries Science Center, NOAA Fisheries, 2021 - 2025
- Graduate Research Assistant, Hawaiʻi Institute of Marine Biology, University of Hawaiʻi at Mānoa, 2021 - Present
- Graduate Research Assistant, Quantitative Ecology & Resource Management, University of Washington, 2016 - 2017
- Graduate Research Assistant, Applied Ecology, North Carolina State University, 2014 - 2016

## Professional Experience

- Data Analyst, Health Services, Deschutes County, 2020 - 2021
- Data Analyst, Supply Chain AI & Machine Learning, Starbucks Coffee Company, 2019
- Quantitative Analyst, Seattle City Light, City of Seattle, 2017 - 2019

## Grants, Awards, and Fellowships

- Peter Castro Graduate Student Research Fund, Hawai‘i Institute of Marine Biology, 2025, $1100
- Colonel Willys E. & Sandina L. Lord Endowed Scholarship, Hawai‘i Institute of Marine Biology, 2024, $500
- Best Student Poster: 2nd Place, International Statistical Ecology Conference, 2024
- Peter Castro HIMB Graduate Student Support Fund - Travel, Hawaiʻi Institute of Marine Biology, 2023, $500
- Linda and Jim Collister Scholarship, Hawaiʻi Institute of Marine Biology, 2023, $1,000
- Quantitative Ecology and Socioeconomic Training Fellowship (QUEST), NOAA Fisheries, 2021 to present, $180,000
- Achievement Scholarship, University of Hawaiʻi at Mānoa, 2023, $500
- Colonel Willys E. & Sandina L. Lord Endowed Scholarship, Hawaiʻi Institute of Marine Biology, 2022, $2,000
- Student Travel Award, University of Washington, 2017, $500
- Student and Postdoc Travel Award, University of Washington, 2017, $750
- Travel Award, University of Washington, 2017, $500
- Global Change Fellowship, USGS, 2015 to 2016, $12,000

## [Papers](https://scholar.google.com/citations?user=4TUtf04AAAAJ&hl=en&oi=ao) 

1. Vanderzee, A., Cheeseman, T., **Patton, P.T.**, & Calambokidis, J. Evaluating a dorsal fin matching algorithm applied to Risso’s dolphins in the Southern California Bight. *In revision*
2. Parnell, K., Smith, C., Diaz, A., Fertitta, K., Thompson, P., **Patton, P.T.**, Charrier, I., Robinson, S.J., Pacini, A. and Bejder, L., 2025. Underwater sound production of free-ranging Hawaiian monk seals. *Royal Society Open Science*, 12(11). [PDF](papers/parnell-2025-monk.pdf)
3. Brijs, J., Moore, C., Schakmann, M., Souza, T., Grellman, K.,  Tran, L.L., **Patton, P.T.**, and Johansen, J.L. (2025) Eat more, often: The capacity of piscivores to meet increased energy demands in warming oceans. *Science of the Total Environment*, 973, 179105. [PDF](papers/brijs-2025-eat.pdf)
4. **Patton, P. T.**, Pacifici, K., Baird, R. W., Oleson, E. M., Allen, J. B., Ashe, E., Athayde, A., Basran, C. J., Cabrera, E., Calambokidis, J., Cardoso, J., Carroll, E. L., Cesario, A., Cheney, B. J., Cheeseman, T., Corsi, E., Currie, J. J., Durban, J. W., Falcone, E. A., … Bejder, L. (2025). Optimizing automated photo identification for population assessments. Conservation Biology, 39, e14436. [PDF](papers/patton-2025-optimal.pdf)
5. **Patton, P. T.**, Cheeseman, T., Abe, K., Yamaguchi, T., Reade, W., Southerland, K., Howard, A., Oleson, E. M., Allen, J. B., Ashe, E., Athayde, A., Baird, R. W., Basran, C., Cabrera, E., Calambokidis, J., Cardoso, J., Carroll, E. L., Cesario, A., Cheney, B. J. ..., Bejder, L. (2023). A deep learning approach to photo‑identification demonstrates high performance on two dozen cetacean species. *Methods in Ecology and Evolution*, 14, 2611–2625 [PDF](papers/patton-2023-deep.pdf)
6. Vivier, F., Wells, R.S., Hill, M.C., Yano, K.M., Bradford, A.L., Leunissen, E.M., Pacini, A., Booth, C.G., Rocho-Levine, J., Currie J.J., **Patton, P.T.**, & Bejder, L. (2023) Quantifying the age-structure of free-ranging delphinid populations: testing the accuracy of Unoccupied Aerial System-photogrammetry. *Ecology and Evolution,* 13, e10082. [PDF](papers/vivier-2023-uas.pdf)
7. **Patton, P. T.**, Pacifici, K., \& Collazo, J. A. (2022) Modeling and estimating co-occurrence between the invasive Shiny Cowbird and its Puerto Rican hosts. *Biological Invasions,* 24, 2951--2960 [PDF](papers/patton-2022-cowbird.pdf)

## Presentations

1. **Patton, P.T.**, Pacifici, K., Allen, J.B., Ashe, E., Athayde, A., Baird, R.W., …& Bejder, L. Evaluating trade‑offs between automation and bias in population assessments relying on photo‑identification. Paper presented at the Biennial Conference on the Biology of Marine Mammals in Perth, Australia. November 2024.
2. Fertitta, K., Diaz, A., Smith, C., **Patton, P.T.**, Parnell, K., Charrier, I., Pacini, A., & Bejder, L. Descriptions of Hawaiian monk seal underwater vocal behavior at Lehua Rock. Poster presented at the Biennial Conference on the Biology of Marine Mammals in Perth, Australia. November 2024
3. Parnell, K., Fertitta, K., Diaz, A., Smith, C., Thompson, P., **Patton, P.T.**, Charrier, I., Barbierri, M., Pacini, A., & Bejder, L. Talking story with ‘īlio holo i ka uaua (Hawaiian monk seals): First descriptions of underwater sound production in free‑ranging individuals. Poster presented at the Biennial Conference on the Biology of Marine Mammals in Perth, Australia. November 2024
4. **Patton, P.T.**, Pacifici, K., Allen, J.B., Ashe, E., Athayde, A., Baird, R.W., …& Bejder, L. Evaluating trade‑offs between automation and bias in population assessments relying on photo‑identification. Poster presented at the International Statistical Ecology Conference. Swansea, Wales. July 2024. Best Student Poster: 2nd Place
5. **Patton, P.T.** Some hierarchical and machine learning models for wildlife science. Invited talk at University of Natural Resources and Life Sciences (BOKU), Vienna, Austria. July 2023.
6. **Patton, P.T.**, Oleson, E.M., Baird, R.W., McPherson, L.M., Mahaffy, S.D., &. Bejder, L. The effect of fully automated photo‑identification on mark-recapture estimates. Paper presented at the EURING Analytical Meeting. Montpellier, France. April 2023
7. **Patton, P. T.** & Gardner, B. Misspecifying movement models in spatial capture recapture studies. Paper presented at The Ecological Society of America Conference. Portland, OR, USA. August 2017
8. **Patton, P. T.**, Pacifici, K., & Collazo, J. A. Modeling and estimating co‑occurrence between generalist brood parasites and host communities. Paper presented at the EURING Analytical Meeting. Barcelona, Spain. June 2017
9. **Patton, P. T.**, Pacifici, K., & Collazo, J. A. Multi‑species occupancy models that incorporate false positive and false negative sampling errors. Paper presented at The Wildlife Society Conference. Raleigh, NC, USA. October 2016
10. **Patton, P. T.**, Pacifici, K., & Collazo, J. A. Joint host‑parasite occurrence models can improve predictions and reveal ecological traps. Paper presented at the International Statistical Ecology Conference. Seattle, WA, USA. July 2016

## Teaching Experience

- Teaching Assistant, Global Climate Data (MBIO 690), University of Hawaiʻi at Mānoa, Spring 2025
- Teaching Assistant, Mathematical Ecology of Marine Systems (MBIO 610), University of Hawaiʻi at Mānoa, Spring 2025
- Teaching Assistant, Introduction to Scientific Computing (MBIO 690), University of Hawaiʻi at Mānoa, Fall 2024
- Teaching Assistant, Principles of Wildlife Science (FW 453), North Carolina State, Spring 2016
- Teaching Assistant, Introduction to Probability and Statistics (APM 391), SUNY ESF, Fall 2012
- Tutor, Calculus I (APM 105), Academic Support Services, SUNY ESF, 2011 to 2013

## Professional Development

- An Introduction to Close-Kin Mark-Recapture, EURING Analytical Meeting
- C++ Virtual Training, NOAA Fisheries
- Bayesian Model Selection and Decision Theory for Ecologists, International Statistical Ecology Conference
- Flexible Programming with NIMBLE, International Statistical Ecology Conference
- Introduction to Structured Decision Making, National Conservation Training Center

## Professional Service

- Referee: *Wildlife Society Bulletin*, *Marine Mammal Science*
- Member: British Ecological Society, The Wildlife Society (biometrics working group), The Ecological Society of America (statistical ecology section)
- Representative to the Faculty, Marine Biology Graduate Program, University of Hawaiʻi at Mānoa
- Representative to the Graduate Student Organization, Marine Biology Graduate Program, University of Hawaiʻi at Mānoa

---
